# Generated by Django 2.2.12 on 2020-04-08 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myimage',
            name='authority',
            field=models.CharField(default='075', max_length=4),
        ),
    ]
