# Generated by Django 2.2.12 on 2020-04-09 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0002_auto_20200408_2034'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagetag',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
