# Generated by Django 2.2.12 on 2020-04-09 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statistic',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
