# Generated by Django 2.2.12 on 2020-05-06 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArticalTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(max_length=7)),
                ('count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Trap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('context', models.CharField(default='计算机相关问题', max_length=200)),
                ('problem', models.CharField(default='一个棘手的问题...', max_length=200)),
                ('solution', models.CharField(default='我想到了一个绝妙的解决方法, 但是这里位置太小, 我写不下...', max_length=700)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('tags', models.ManyToManyField(to='artical.ArticalTag')),
            ],
            options={
                'ordering': ['last_update'],
            },
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('content', models.TextField(max_length=5000)),
                ('headline', models.CharField(max_length=20)),
                ('tags', models.ManyToManyField(to='artical.ArticalTag')),
            ],
            options={
                'ordering': ['last_update'],
            },
        ),
    ]
