# Generated by Django 2.2.12 on 2020-04-08 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artical', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='headline',
            field=models.CharField(default='我是标题', max_length=20),
            preserve_default=False,
        ),
    ]
