# Generated by Django 2.2.12 on 2020-05-12 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artical', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trap',
            name='solution',
            field=models.TextField(default='我想到了一个绝妙的解决方法, 但是这里位置太小, 我写不下...', max_length=700),
        ),
    ]
