# Generated by Django 2.2.12 on 2020-04-08 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artical', '0002_blog_headline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articaltag',
            name='tag_name',
            field=models.CharField(max_length=7),
        ),
    ]
