# Generated by Django 2.2.12 on 2020-05-06 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artical', '0004_articaltag_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='tags',
            field=models.ManyToManyField(null=True, to='artical.ArticalTag'),
        ),
    ]
