# Generated by Django 2.2.12 on 2020-05-13 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artical', '0005_auto_20200512_1516'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ['-last_update']},
        ),
        migrations.AlterModelOptions(
            name='trap',
            options={'ordering': ['-last_update']},
        ),
    ]
