# Generated by Django 2.2.12 on 2020-05-10 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorize', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visiter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=260)),
                ('authority', models.CharField(default='075', max_length=4)),
            ],
        ),
    ]
