# Generated by Django 2.2.12 on 2020-05-10 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorize', '0002_visiter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visiter',
            name='authority',
            field=models.CharField(default='070', max_length=4),
        ),
    ]
