# Generated by Django 2.2.12 on 2020-05-10 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorize', '0004_visiter_expire'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='visiter',
            options={'ordering': ['-expire']},
        ),
        migrations.AlterField(
            model_name='visiter',
            name='expire',
            field=models.DateTimeField(null=True),
        ),
    ]
